DROP TABLE MIPS_BRA.DBO.ACRAD41_PET_2024

SELECT 
CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101) AS APPOINTMENTDATE
, '061613357' as TIN
, NPI
, RAD AS READING_RADIOLOGIST
, MRN
, [Patient Name] AS PATIENT_NAME
 , CONVERT(int,ROUND(DATEDIFF(hour,BirthDate,CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101)) /8766.0,0)) as PATIENT_AGE
, SEX
, CASE WHEN INSURANCE LIKE '%MEDICARE%' THEN 'Y' ELSE 'N' END AS PATIENT_MEDICARE_BENEFICIARY
, CASE WHEN (INSURANCE  LIKE '%MEDICARE%' 
        AND (INSURANCE NOT LIKE '%HARVARD PILGRIM%' OR INSURANCE NOT LIKE '%HARVARD PILGRIM UNITED%' OR INSURANCE NOT LIKE '%HUMANA%' 
                OR INSURANCE NOT LIKE '%HUMANA - GENERIC%' OR INSURANCE NOT LIKE '%HUMANA MEDICARE GENERIC5' OR INSURANCE NOT LIKE '%HUMANA MGD MEDICARE%' 
                OR INSURANCE NOT LIKE '%HUMANA - LEXINGTON%' OR INSURANCE NOT LIKE '%OXFORD HEALTH PLAN%' OR INSURANCE NOT LIKE '%EMPIRE BLUECROSS BLUESHIELD%' 
                OR INSURANCE NOT LIKE '%HORIZON BCBSNJ%' OR INSURANCE NOT LIKE '%ANTHEM EMPIRE BCBS%' OR INSURANCE NOT LIKE '%ANTHEM FEP BCBS CT%' 
                OR INSURANCE NOT LIKE '%ANTHEM NATIONAL BCBS CT%' OR INSURANCE NOT LIKE '%CIGNA ALL%' OR INSURANCE NOT LIKE '%CIGNA - GENERIC%' 
                OR INSURANCE NOT LIKE '%CIGNA BEHAVIORAL HEALTH%'OR INSURANCE NOT LIKE '%CIGNA GENERIC%' OR INSURANCE NOT LIKE '%CIGNA HMO%' 
                OR INSURANCE NOT LIKE '%CIGNA MGD MEDICARE%' OR INSURANCE NOT LIKE '%CIGNA OSCAR%' OR INSURANCE NOT LIKE '%CIGNA PPO%' 
                OR INSURANCE NOT LIKE '%OXFORD HEALTH PLANS%' OR INSURANCE NOT LIKE '%AETNA - HMO-MEDICARE AND ALL OTHERS%' OR INSURANCE NOT LIKE '%AETNA HMO%' 
                OR INSURANCE NOT LIKE '%AETNA HMO/POS%' OR INSURANCE NOT LIKE '%AETNA ADVANTAGE PLANS OFF EXCHANGE%' OR INSURANCE NOT LIKE '%AETNA MEDICARE ADVANTAGE%' 
                OR INSURANCE NOT LIKE '%AETNA ADVANTAGE PLANS/AETNA OPEN ACCESS%') 
        AND CONVERT(int,ROUND(DATEDIFF(hour,BirthDate,CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101)) /8766.0,0))  >= 65) 
    THEN 'Y' ELSE 'N' END AS PATIENT_MEDICARE_ADVANTAGE
,'ACRAD41' as MEASURE_NUMBER
, [Exam Name] AS APPOINTMENTREASON
, CPT as CPT_CODE
, '' as DENOMINATOR_DIAGNOSIS_CODE
, ACCESSION
, LEFT([EXAM NAME], 2) AS MODALITY
, NUMERATOR_RESPONSE_VALUE
, '' AS MEASURE_EXTENSION_NUM
, '' AS EXTENSION_RESPONSE_VALUE
INTO MIPS_BRA.DBO.ACRAD41_PET_2024
FROM
(select distinct 
BH_ExamDetails.[Patient Name]
, BH_ExamDetails.[Visit Type]
, BH_ExamDetails.[Exam Name]
, BH_ExamDetails.[Reason For Exam]
, BH_ExamDetails.[Exam Date]
, BH_ExamDetails.[Referring Physician]
,BH_Powerscribe2.NPI
, BH_ExamDetails.[Rad]
, BH_ExamDetails.[Report Sign Date]
, BH_ExamDetails.[Exam Location]
, BH_ExamDetails.[ACCESSION]
, BH_ExamDetails.[MRN]
, CONVERT(int,ROUND(DATEDIFF(hour,BirthDate,CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101)) /8766.0,0)) as PATIENT_AGE
, BH_ExamDetails.BirthDate
, BH_Powerscribe2.SEX
, BRIDGEPORT_BPI.[Custom Payor Name (Original)] AS INSURANCE
,  CASE WHEN (CONCAT(REPORTA, REPORTB) LIKE '%Blood glucose%') 
            AND (CONCAT(REPORTA, REPORTB) like '%background uptake%') 
            AND (CONCAT(REPORTA, REPORTB) like '%uptake time%' 
                    OR  CONCAT(REPORTA, REPORTB) like '%minutes following tracer administration PET imaging%') 
            AND (REPORTA like '%maximum SUV%' 
                    or CONCAT(REPORTA, REPORTB) like '%SUV max of%' 
                    or CONCAT(REPORTA, REPORTB) like '%(SUVmax%' 
                    or CONCAT(REPORTA, REPORTB) like '%with max SUV%' 
                    or CONCAT(REPORTA, REPORTB) like '%No disease-specific abnormal uptake%' 
                    or CONCAT(REPORTA, REPORTB) like '%No other disease-specific abnormal uptake is identified%'
			        or CONCAT(REPORTA, REPORTB) like '%, max SUV%'
			  )  
	THEN 'Y' ELSE 'N' END AS NUMERATOR_RESPONSE_VALUE
, BRIDGEPORT_COMPENDIUM.CPT
from ARC_DW.dbo.BH_ExamDetails
inner join ARC_DW.dbo.BH_Reports on BH_ExamDetails.Accession = BH_Reports.Accession
left outer join ARC_DW.dbo.Bridgeport_Compendium on BH_ExamDetails.[Exam Name] = Bridgeport_Compendium.[Exam Name]
LEFT OUTER JOIN MPF.DBO.BH_POWERSCRIBE2 ON BH_EXAMDETAILS.ACCESSION = BH_POWERSCRIBE2.FILLERORDERNUMBER
LEFT OUTER JOIN MPF.DBO.BRIDGEPORT_BPI ON BH_EXAMDETAILS.ACCESSION = BRIDGEPORT_BPI.[Original Record Number]
where Bridgeport_Compendium.cpt in ('78811','78812','78813','78814','78815','78816','G0219','G0235','G0252')
AND (CONCAT(REPORTA, REPORTB) NOT LIKE '%ALZHEIMER%')) a
;
