DROP TABLE IF EXISTS MIPS_BRA.DBO.ACRAD37_PE_2024

SELECT DISTINCT
CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101) AS APPOINTMENTDATE
, '061613357' as TIN
, CASE WHEN RAD = 'FERRANTE, MARC,MD' THEN '1932462629'
WHEN RAD = 'WILLIAMS, SCOTT C,MD' THEN '1457347833'
WHEN RAD = 'ROTEM, ERAN,MD' THEN '1912294182'
WHEN RAD = 'HUGHES, TERENCE W,MD' THEN '1053307421'
WHEN RAD = 'VELASCO, NOEL B,MD' THEN '1922093590'
WHEN RAD = 'KAYE, ADAM,MD' THEN '1881838118'
WHEN RAD = 'MARRINAN, GREG B,MD' THEN '1942295506'
WHEN RAD = 'ROSASCO, SARAH LYLA,MD' THEN '1881980084'
WHEN RAD = 'ZINN, KENNETH M,MD' THEN '1609861285'
WHEN RAD = 'VELASCO, JOHN-PAUL,MD' THEN '1861712309'
ELSE NPI END NPI -- These doctors have multiple NPIs so for consistency, hard coding NPI 
, RAD AS READING_RADIOLOGIST
, MRN
, [Patient Name] AS PATIENT_NAME
, CONVERT(int,ROUND(DATEDIFF(hour,BirthDate,CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101)) /8766.0,0)) as PATIENT_AGE
, CASE WHEN SEX IS NULL THEN 'U' ELSE SEX END AS SEX
, CASE WHEN INSURANCE LIKE '%MEDICARE%' THEN 'Y' ELSE 'N' END AS PATIENT_MEDICARE_BENEFICIARY
, CASE WHEN (INSURANCE  LIKE '%MEDICARE%' 
	and (INSURANCE NOT LIKE '%HARVARD PILGRIM%' OR INSURANCE NOT LIKE '%HARVARD PILGRIM UNITED%' OR INSURANCE NOT LIKE '%HUMANA%' OR INSURANCE NOT LIKE '%HUMANA - GENERIC%' OR INSURANCE NOT LIKE '%HUMANA MEDICARE GENERIC5' 
		OR INSURANCE NOT LIKE '%HUMANA MGD MEDICARE%' OR INSURANCE NOT LIKE '%HUMANA - LEXINGTON%' OR INSURANCE NOT LIKE '%OXFORD HEALTH PLAN%' OR INSURANCE NOT LIKE '%EMPIRE BLUECROSS BLUESHIELD%' OR INSURANCE NOT LIKE '%HORIZON BCBSNJ%' 
		OR INSURANCE NOT LIKE '%ANTHEM EMPIRE BCBS%' OR INSURANCE NOT LIKE '%ANTHEM FEP BCBS CT%' OR INSURANCE NOT LIKE '%ANTHEM NATIONAL BCBS CT%' OR INSURANCE NOT LIKE '%CIGNA ALL%' OR INSURANCE NOT LIKE '%CIGNA - GENERIC%' 
		OR INSURANCE NOT LIKE '%CIGNA BEHAVIORAL HEALTH%'OR INSURANCE NOT LIKE '%CIGNA GENERIC%' OR INSURANCE NOT LIKE '%CIGNA HMO%' OR INSURANCE NOT LIKE '%CIGNA MGD MEDICARE%' OR INSURANCE NOT LIKE '%CIGNA OSCAR%' OR INSURANCE NOT LIKE '%CIGNA PPO%' 
		OR INSURANCE NOT LIKE '%OXFORD HEALTH PLANS%' OR INSURANCE NOT LIKE '%AETNA - HMO-MEDICARE AND ALL OTHERS%' OR INSURANCE NOT LIKE '%AETNA HMO%' OR INSURANCE NOT LIKE '%AETNA HMO/POS%' OR INSURANCE NOT LIKE '%AETNA ADVANTAGE PLANS OFF EXCHANGE%'
		OR INSURANCE NOT LIKE '%AETNA MEDICARE ADVANTAGE%' OR INSURANCE NOT LIKE '%AETNA ADVANTAGE PLANS/AETNA OPEN ACCESS%')    
	AND CONVERT(int,ROUND(DATEDIFF(hour,BirthDate,CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101)) /8766.0,0))  >= 65)
	THEN 'Y' ELSE 'N' END AS PATIENT_MEDICARE_ADVANTAGE
,'ACRAD37' as MEASURE_NUMBER
, [Exam Name] AS APPOINTMENTREASON
, CPT as CPT_CODE
, '' as DENOMINATOR_DIAGNOSIS_CODE
, ACCESSION
, LEFT([EXAM NAME], 2) AS MODALITY
, NUMERATOR_RESPONSE_VALUE
, '' AS MEASURE_EXTENSION_NUM
, '' AS EXTENSION_RESPONSE_VALUE
INTO MIPS_BRA.DBO.ACRAD37_PE_2024
FROM
(
SELECT DISTINCT
BH_ExamDetails.[Patient Name]
, BH_ExamDetails.[Visit Type]
, BH_ExamDetails.[Exam Name]
, BH_ExamDetails.[Reason For Exam]
, BH_ExamDetails.[Exam Date]
, BH_ExamDetails.[Referring Physician]
, BH_Powerscribe2.NPI
, BH_ExamDetails.[Rad]
, BH_ExamDetails.[Report Sign Date]
, BH_ExamDetails.[Exam Location]
, BH_ExamDetails.[ACCESSION]
, BH_ExamDetails.[MRN]
, CONVERT(int,ROUND(DATEDIFF(hour,BirthDate,CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101)) /8766.0,0)) as PATIENT_AGE
, BH_ExamDetails.BirthDate
, BH_Powerscribe2.SEX
, BRIDGEPORT_BPI.[Custom Payor Name (Original)] AS INSURANCE
, BRIDGEPORT_COMPENDIUM.CPT
, CASE WHEN (R.pass_measure IS NOT NULL) THEN 'Y' ELSE 'N' END AS NUMERATOR_RESPONSE_VALUE
from ARC_DW.dbo.BH_ExamDetails
INNER JOIN
(SELECT DISTINCT ACCESSION, 
-- Does the report have at least one of the phrases in it. if so, pass_measure will return the first phrase found
(SELECT TOP 1 PHRASE FROM ARC_DW.DBO.REPORT_PHRASES
	WHERE CRITERIA = 'Y' AND MEASURE = 'ACRAD37'
	and CONCAT(ReportA, ReportB) LIKE CONCAT('%',REPORT_PHRASES.PHRASE,'%')
) pass_measure
FROM ARC_DW.dbo.BH_Reports
-- filter out any reports that have a phrase that should be excluded from the denominator 
WHERE NOT EXISTS (select top 1 PHRASE FROM ARC_DW.DBO.REPORT_PHRASES
	WHERE denominator = 'EXCLUDE' AND MEASURE = 'ACRAD37'
	and CONCAT(ReportA, ReportB) LIKE CONCAT('%',REPORT_PHRASES.PHRASE,'%'))
) AS R 
ON BH_ExamDetails.Accession = R.Accession
left outer join ARC_DW.dbo.Bridgeport_Compendium on BH_ExamDetails.[Exam Name] = Bridgeport_Compendium.[Exam Name]
LEFT OUTER JOIN MPF.DBO.BH_POWERSCRIBE2 ON BH_EXAMDETAILS.ACCESSION = BH_POWERSCRIBE2.FILLERORDERNUMBER
LEFT OUTER JOIN MPF.DBO.BRIDGEPORT_BPI ON BH_EXAMDETAILS.ACCESSION = BRIDGEPORT_BPI.[Original Record Number]
where Bridgeport_Compendium.cpt in ('71275')  
) AS A
WHERE A.PATIENT_AGE >= 18 
AND A.[Exam Name] LIKE '%(PE)%'
;

