USE ARC_DW;
DROP TABLE IF EXISTS MIPS_BRA.[dbo].[CAT_436_2024]
SELECT DISTINCT 
CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101) AS APPOINTMENTDATE
, '061613357' as TIN
, NPI
, RAD AS READING_RADIOLOGIST
, MRN
, [Patient Name] AS PATIENT_NAME
, CONVERT(int,ROUND(DATEDIFF(hour,BirthDate,CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101)) /8766.0,0)) as PATIENT_AGE
, SEX
, CASE WHEN INSURANCE LIKE '%MEDICARE%' THEN 'Y' ELSE 'N' END AS PATIENT_MEDICARE_BENEFICIARY
, CASE WHEN (INSURANCE  LIKE '%MEDICARE%' 
    AND (INSURANCE NOT LIKE '%HARVARD PILGRIM%' OR INSURANCE NOT LIKE '%HARVARD PILGRIM UNITED%' OR INSURANCE NOT LIKE '%HUMANA%' OR INSURANCE NOT LIKE '%HUMANA - GENERIC%' 
        OR INSURANCE NOT LIKE '%HUMANA MEDICARE GENERIC5' OR INSURANCE NOT LIKE '%HUMANA MGD MEDICARE%' OR INSURANCE NOT LIKE '%HUMANA - LEXINGTON%' 
        OR INSURANCE NOT LIKE '%OXFORD HEALTH PLAN%' OR INSURANCE NOT LIKE '%EMPIRE BLUECROSS BLUESHIELD%' OR INSURANCE NOT LIKE '%HORIZON BCBSNJ%' 
        OR INSURANCE NOT LIKE '%ANTHEM EMPIRE BCBS%' OR INSURANCE NOT LIKE '%ANTHEM FEP BCBS CT%' OR INSURANCE NOT LIKE '%ANTHEM NATIONAL BCBS CT%' 
        OR INSURANCE NOT LIKE '%CIGNA ALL%' OR INSURANCE NOT LIKE '%CIGNA - GENERIC%' OR INSURANCE NOT LIKE '%CIGNA BEHAVIORAL HEALTH%'OR INSURANCE NOT LIKE '%CIGNA GENERIC%' 
        OR INSURANCE NOT LIKE '%CIGNA HMO%' OR INSURANCE NOT LIKE '%CIGNA MGD MEDICARE%' OR INSURANCE NOT LIKE '%CIGNA OSCAR%' OR INSURANCE NOT LIKE '%CIGNA PPO%' 
        OR INSURANCE NOT LIKE '%OXFORD HEALTH PLANS%' OR INSURANCE NOT LIKE '%AETNA - HMO-MEDICARE AND ALL OTHERS%' OR INSURANCE NOT LIKE '%AETNA HMO%' 
        OR INSURANCE NOT LIKE '%AETNA HMO/POS%' OR INSURANCE NOT LIKE '%AETNA ADVANTAGE PLANS OFF EXCHANGE%'
        OR INSURANCE NOT LIKE '%AETNA MEDICARE ADVANTAGE%' OR INSURANCE NOT LIKE '%AETNA ADVANTAGE PLANS/AETNA OPEN ACCESS%')  
    AND CONVERT(int,ROUND(DATEDIFF(hour,BirthDate,CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101)) /8766.0,0))  >= 65) 
    THEN 'Y' ELSE 'N' END AS PATIENT_MEDICARE_ADVANTAGE
,'436' as MEASURE_NUMBER
, [Exam Name] AS APPOINTMENTREASON
, CPT  as CPT_CODE
, '' as DENOMINATOR_DIAGNOSIS_CODE
, ACCESSION
, LEFT([EXAM NAME], 2) AS MODALITY
, CASE WHEN (performance_met IS NOT NULL)
    THEN 'G9637' ELSE 'G9638' END
, '' AS MEASURE_EXTENSION_NUM
, '' AS EXTENSION_RESPONSE_VALUE
INTO MIPS_BRA.[dbo].[CAT_436_2024]
FROM (
	SELECT DISTINCT
	BH_ExamDetails.[Patient Name] 
	, BH_ExamDetails.[Visit Type]
	, BH_ExamDetails.[Exam Name]
	, BH_ExamDetails.[Reason For Exam]
	, BH_ExamDetails.[Exam Date] 
	, BH_ExamDetails.[Referring Physician]
	, BH_Powerscribe2.NPI
	, BH_ExamDetails.[Rad] 
	, BH_ExamDetails.[Report Sign Date]
	, BH_ExamDetails.[Exam Location]
	, BH_ExamDetails.[ACCESSION]
	, BH_ExamDetails.[MRN]
	, BH_ExamDetails.BirthDate
	, BH_Powerscribe2.SEX
	, BRIDGEPORT_BPI.[Custom Payor Name (Original)] AS INSURANCE
	, BRIDGEPORT_COMPENDIUM.CPT
	, R.performance_met
    -- MARK COMPLIANCE USING REPORT PHRASES QUERY 
	FROM (SELECT DISTINCT BH_Reports.ACCESSION, 
            (SELECT TOP 1 PHRASE FROM ARC_DW.DBO.REPORT_PHRASES
	            WHERE CRITERIA = 'Y' AND MEASURE = '436'
	            and CONCAT(BH_Reports.ReportA, BH_Reports.ReportB) LIKE CONCAT('%',REPORT_PHRASES.PHRASE,'%')
                ) performance_met
        FROM ARC_DW.dbo.BH_Reports 
    ) AS R
    INNER JOIN ARC_DW.dbo.BH_ExamDetails ON R.ACCESSION = BH_ExamDetails.Accession
	left outer join ARC_DW.dbo.Bridgeport_Compendium on BH_ExamDetails.[Exam Name] = Bridgeport_Compendium.[Exam Name]
	LEFT OUTER JOIN MPF.DBO.BH_POWERSCRIBE2 ON BH_EXAMDETAILS.ACCESSION = BH_POWERSCRIBE2.FILLERORDERNUMBER
	LEFT OUTER JOIN MPF.DBO.BRIDGEPORT_BPI ON BH_EXAMDETAILS.ACCESSION = BRIDGEPORT_BPI.[Original Record Number]
	WHERE Year(BH_ExamDetails.[Report Sign Date]) = '2024' 
    AND Bridgeport_Compendium.cpt in ('70450', '70460', '70470', '70480',
	    '70481', '70482', '70486', '70487', '70488', '70490', '70491', '70492', '70496', '70498', '71250', '71260', '71270',
	    '71271', '71275', '72125', '72126', '72127', '72128', '72129', '72130', '72131', '72132', '72133', '72191', '72192',
	    '72193', '72194', '73200', '73201', '73202', '73206', '73700', '73701', '73702', '73706', '74150', '74160', '74170',
	    '74174', '74175', '74176', '74177', '74178', '74261', '74262', '74263', '75571', '75572', '75573', '75574', '75635',
	    '76380', '76497', '77011', '77012', '77013', '77014', '77078', '0042T')
	) A
WHERE CONVERT(int,ROUND(DATEDIFF(hour,BH_ExamDetails.BirthDate,CONVERT(VARCHAR(12), CAST(BH_ExamDetails.[EXAM DATE] AS DATE), 101)) /8766.0,0)) >= 18
;

-- TO DO: NEED TO ADD AN UPDATE QUERY FOR BH EXAMS. 