WITH A_CTE (FillerOrderNumber, ContentText, READING_RADIOLOGIST)
AS (
SELECT BH_Reports.ACCESSION AS FillerOrderNumber, CONCAT(ReportA, ReportB) AS ContentText, Rad AS READING_RADIOLOGIST
FROM ARC_DW.dbo.BH_Reports 
JOIN ARC_DW.dbo.BH_ExamDetails AS E
	ON E.ACCESSION = BH_Reports.ACCESSION
)

SELECT *
FROM 
(
SELECT ACCESSION, ContentText, F.READING_RADIOLOGIST, F.MRN, F.APPOINTMENTDATE, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.ACRAD36_CORONARYARTERY_2024 AS F
INNER JOIN A_CTE
	ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

UNION

SELECT ACCESSION, ContentText, F.READING_RADIOLOGIST, F.MRN, F.APPOINTMENTDATE, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.ACRAD37_PE_2024 AS F
INNER JOIN A_CTE
ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

UNION

SELECT ACCESSION, ContentText, F.READING_RADIOLOGIST, F.MRN, F.APPOINTMENTDATE, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.ACRAD41_PET_2024 AS F
INNER JOIN A_CTE
ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

UNION

SELECT ACCESSION, ContentText, F.READING_RADIOLOGIST, F.MRN, F.APPOINTMENTDATE, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.CAT_436_2024 AS F
INNER JOIN A_CTE
ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

UNION

SELECT ACCESSION, ContentText, F.READING_RADIOLOGIST, F.MRN, F.APPOINTMENTDATE, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.INCIDENTAL_THYROID_NODULES_406_2024 AS F
INNER JOIN A_CTE
ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

UNION

SELECT ACCESSION, ContentText, F.READING_RADIOLOGIST, F.MRN, F.APPOINTMENTDATE, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.MSN_13_2024 AS F
INNER JOIN A_CTE
ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

) A
WHERE 1=1
--NUMERATOR_RESPONSE_VALUE IN ('N', 'PNM01', 'G9554', 'G9550', 'G9638')
AND ACCESSION LIKE 'E%'
AND CAST(APPOINTMENTDATE AS DATE) >= '2024-04-22'
AND Organization NOT LIKE 'TRS'
ORDER BY MEASURE_NUMBER, ACCESSION;

