DROP TABLE MIPS_BRA.DBO.MSN_13_2024;

select  DISTINCT
CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101) AS APPOINTMENTDATE
, '061613357' as TIN
, CASE WHEN RAD = 'FERRANTE, MARC,MD' THEN '1932462629'
       WHEN RAD = 'WILLIAMS, SCOTT C,MD' THEN '1457347833'
	   WHEN RAD = 'ROTEM, ERAN,MD' THEN '1912294182'
	   WHEN RAD = 'HUGHES, TERENCE W,MD' THEN '1053307421'
	   WHEN RAD = 'VELASCO, NOEL B,MD' THEN '1922093590'
	   WHEN RAD = 'KAYE, ADAM,MD' THEN '1881838118'
	   WHEN RAD = 'MARRINAN, GREG B,MD' THEN '1942295506'
	   WHEN RAD = 'ROSASCO, SARAH LYLA,MD' THEN '1881980084'
	   WHEN RAD = 'ZINN, KENNETH M,MD' THEN '1609861285'
	   WHEN RAD = 'VELASCO, JOHN-PAUL,MD' THEN '1861712309'
	   ELSE NPI END NPI
, RAD AS READING_RADIOLOGIST
, MRN
, [Patient Name] AS PATIENT_NAME
 , CONVERT(int,ROUND(DATEDIFF(hour,BirthDate,CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101)) /8766.0,0)) as PATIENT_AGE
, CASE WHEN SEX IS NULL THEN 'U' ELSE SEX END AS SEX
, CASE WHEN INSURANCE LIKE '%MEDICARE%' THEN 'Y' ELSE 'N' END AS PATIENT_MEDICARE_BENEFICIARY
, CASE WHEN (INSURANCE  LIKE '%MEDICARE%' 
        and (INSURANCE NOT LIKE '%HARVARD PILGRIM%' OR INSURANCE NOT LIKE '%HARVARD PILGRIM UNITED%' 
            OR INSURANCE NOT LIKE '%HUMANA%' OR INSURANCE NOT LIKE '%HUMANA - GENERIC%' 
            OR INSURANCE NOT LIKE '%HUMANA MEDICARE GENERIC5' OR INSURANCE NOT LIKE '%HUMANA MGD MEDICARE%' 
            OR INSURANCE NOT LIKE '%HUMANA - LEXINGTON%' OR INSURANCE NOT LIKE '%OXFORD HEALTH PLAN%'
            OR INSURANCE NOT LIKE '%EMPIRE BLUECROSS BLUESHIELD%' OR INSURANCE NOT LIKE '%HORIZON BCBSNJ%' 
            OR INSURANCE NOT LIKE '%ANTHEM EMPIRE BCBS%' OR INSURANCE NOT LIKE '%ANTHEM FEP BCBS CT%' 
            OR INSURANCE NOT LIKE '%ANTHEM NATIONAL BCBS CT%' OR INSURANCE NOT LIKE '%CIGNA ALL%' 
            OR INSURANCE NOT LIKE '%CIGNA - GENERIC%' OR INSURANCE NOT LIKE '%CIGNA BEHAVIORAL HEALTH%'
            OR INSURANCE NOT LIKE '%CIGNA GENERIC%' OR INSURANCE NOT LIKE '%CIGNA HMO%' 
            OR INSURANCE NOT LIKE '%CIGNA MGD MEDICARE%' OR INSURANCE NOT LIKE '%CIGNA OSCAR%' 
            OR INSURANCE NOT LIKE '%CIGNA PPO%' OR INSURANCE NOT LIKE '%OXFORD HEALTH PLANS%' 
            OR INSURANCE NOT LIKE '%AETNA - HMO-MEDICARE AND ALL OTHERS%' OR INSURANCE NOT LIKE '%AETNA HMO%' 
            OR INSURANCE NOT LIKE '%AETNA HMO/POS%' OR INSURANCE NOT LIKE '%AETNA ADVANTAGE PLANS OFF EXCHANGE%'
            OR INSURANCE NOT LIKE '%AETNA MEDICARE ADVANTAGE%' OR INSURANCE NOT LIKE '%AETNA ADVANTAGE PLANS/AETNA OPEN ACCESS%')  
        AND CONVERT(int,ROUND(DATEDIFF(hour,BirthDate,CONVERT(VARCHAR(12), CAST([EXAM DATE] AS DATE), 101)) /8766.0,0))  >= 65) 
    THEN 'Y' ELSE 'N' END AS PATIENT_MEDICARE_ADVANTAGE
,'MSN13' as MEASURE_NUMBER
, [Exam Name] AS APPOINTMENTREASON
, CPT as CPT_CODE
, '' as DENOMINATOR_DIAGNOSIS_CODE
, ACCESSION
, LEFT([EXAM NAME], 2) AS MODALITY
, CASE WHEN ((REPORT LIKE '%Calcium Score%' or REPORT like '%CACS%') 
        and (REPORT like '%Left Main%' or REPORT like '%LM:%' or REPORT like '%LM%') 
        and REPORT like '%LAD%' and REPORT like '%LCx%' and REPORT like '%RCA%' and REPORT like '%PDA%'
    ) THEN 'PM001' ELSE 'PNM01' END AS NUMERATOR_RESPONSE_VALUE
, '' AS MEASURE_EXTENSION_NUM
, '' AS EXTENSION_RESPONSE_VALUE
INTO MIPS_BRA.DBO.MSN_13_2024
from
(
    SELECT DISTINCT
    BH_ExamDetails.[Patient Name]
    , BH_ExamDetails.[Visit Type]
    , BH_ExamDetails.[Exam Name]
    , BH_ExamDetails.[Reason For Exam]
    , BH_ExamDetails.[Exam Date]
    , BH_ExamDetails.[Referring Physician]
    , BH_Powerscribe2.NPI
    , BH_ExamDetails.[Rad]
    , BH_ExamDetails.[Report Sign Date]
    , BH_ExamDetails.[Exam Location]
    , BH_ExamDetails.[ACCESSION]
    , BH_ExamDetails.[MRN]
    , BH_ExamDetails.BirthDate
    , BH_Powerscribe2.SEX
    , BRIDGEPORT_BPI.[Custom Payor Name (Original)] AS INSURANCE
    , CONCAT(BH_Reports.ReportA, BH_Reports.ReportB) AS REPORT
    , BRIDGEPORT_COMPENDIUM.CPT
    FROM ARC_DW.dbo.BH_ExamDetails
    inner join ARC_DW.dbo.BH_Reports on BH_ExamDetails.Accession = BH_Reports.Accession
    left outer join ARC_DW.dbo.Bridgeport_Compendium on BH_ExamDetails.[Exam Name] = Bridgeport_Compendium.[Exam Name]
    LEFT OUTER JOIN MPF.DBO.BH_POWERSCRIBE2 ON BH_EXAMDETAILS.ACCESSION = BH_POWERSCRIBE2.FILLERORDERNUMBER
    LEFT OUTER JOIN MPF.DBO.BRIDGEPORT_BPI ON BH_EXAMDETAILS.ACCESSION = BRIDGEPORT_BPI.[Original Record Number]
    where Year(BH_ExamDetails.[Report Sign Date]) = '2024' 
        and Bridgeport_Compendium.cpt in ('75571')
        and CONCAT(BH_Reports.ReportA, BH_Reports.ReportB) not like '%calcium score is 0%' 
)a
ORDER BY ACCESSION

