WITH A_CTE (MRN, LastModifiedDate, ContentText, FillerOrderNumber, Addendum)
AS (
SELECT MRN, O.LastModifiedDate, REPORT.ContentText, FillerOrderNumber , addend.ContentText AS Addendum
FROM COMM4_HHC.dbo.[Order] AS O
JOIN COMM4_HHC.dbo.Report AS REPORT
	ON O.ReportID = REPORT.ReportID
JOIN COMM4_HHC.[dbo].[Visit] AS V
	ON O.VisitID = V.VisitID
JOIN COMM4_HHC.dbo.Patient AS P
	ON V.PatientID = P.PatientID
LEFT OUTER JOIN comm4_hhc.dbo.ReportEvent as RE 
	ON re.ReportID = REPORT.ReportID
LEFT OUTER JOIN Comm4_hhc.dbo.reportaddendum 
	ON REPORT.reportid = reportaddendum.OriginalReportID
LEFT OUTER JOIN Comm4_hhc.dbo.report addend 
	ON addend.reportid = reportaddendum.AddendumReportID
)

SELECT *
FROM 
(
SELECT ACCESSION, ContentText, A_CTE.Addendum, READING_RADIOLOGIST, F.MRN, LastModifiedDate, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.ACRAD36_CORONARYARTERY_2024 AS F
INNER JOIN A_CTE
	ON A_CTE.FillerOrderNumber = ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

UNION

SELECT ACCESSION, ContentText, Addendum, READING_RADIOLOGIST, F.MRN, LastModifiedDate, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.ACRAD37_PE_2024 AS F
INNER JOIN A_CTE
ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

UNION

SELECT ACCESSION, ContentText, Addendum, READING_RADIOLOGIST, F.MRN, LastModifiedDate, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.ACRAD41_PET_2024 AS F
INNER JOIN A_CTE
ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

UNION

SELECT ACCESSION, ContentText, Addendum, READING_RADIOLOGIST, F.MRN, LastModifiedDate, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.CAT_436_2024 AS F
INNER JOIN A_CTE
ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

UNION

SELECT ACCESSION, ContentText, Addendum, READING_RADIOLOGIST, F.MRN, LastModifiedDate, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.INCIDENTAL_THYROID_NODULES_406_2024 AS F
INNER JOIN A_CTE
ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

UNION

SELECT ACCESSION, ContentText, Addendum, READING_RADIOLOGIST, F.MRN, LastModifiedDate, NUMERATOR_RESPONSE_VALUE, MEASURE_NUMBER, Organization
FROM MIPS_BRA.dbo.MSN_13_2024 AS F
INNER JOIN A_CTE
ON A_CTE.FillerOrderNumber = F.ACCESSION
LEFT OUTER JOIN ARC_DW.[dbo].ARC_rads AS AR 
	ON F.NPI = AR.NPI

) A
WHERE NUMERATOR_RESPONSE_VALUE IN ('N', 'PNM01', 'G9554', 'G9550', 'G9638')
AND ACCESSION LIKE 'SV%'
AND LastModifiedDate >= '04/20/2024'
AND Organization NOT LIKE 'TRS'
ORDER BY MEASURE_NUMBER, ACCESSION;